[bpf.thread_tracker]

[bpf.profiler]
frequency = 99
kernel_samples = false
user_samples = true
filter_process = ["monad-node"]

[bpf.schedtrace]
filter_process = ["monad-node"]


[[user]]
socket = "/home/dshulyak/monad-integration/logs/1node-full-20250708_022608-2e95602706a9e1ed/node0/manytrace/node.sock"
log_filter = "debug,monad_node=trace,monad_dataplane=trace"
random_process_id = true