buffer_size = 2097152

[bpf.profiler]
sample_freq = 999
kernel_samples = true
user_samples = true
filter_process = ["continuous"]

[bpf.thread_tracker]

[bpf.cpu_util]
interval_ms = 100
filter_process = ["continuous"]
