[package]
name = "protocol"
version.workspace = true
edition.workspace = true

[dependencies]
rkyv.workspace = true
bitcode.workspace = true

[dev-dependencies]
divan.workspace = true
rstest.workspace = true

[[bench]]
name = "counter"
harness = false