[package]
name = "mpscbuf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
loom = ["dep:loom"]

[dependencies]
crossbeam.workspace = true
eyre.workspace = true
libc.workspace = true
nix.workspace = true
spinning_top.workspace = true
thiserror.workspace = true
loom = { version = "0.7.2", optional = true }

[dev-dependencies]
rstest.workspace = true
