[package]
name = "perfetto-format"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
bytes = "1.6"
protocol = { path = "../protocol" }

[build-dependencies]
prost-build = "0.13"

[dev-dependencies]
anyhow = "1.0"
thread-id = "5.0"